version: '3.8'

services:
  db:
    image: postgres:16-bookworm # 안정적인 Bookworm 버전 권장 이미지를 온라인에서 가져와서 사용
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - linux-project-net
    volumes:
      - postgres-linux-team-data:/var/lib/postgresql/data # 데이터 보존을 위한 볼륨

  api:
    build:
      context: ..
      dockerfile: .devcontainer/fastapi_env/Dockerfile
    env_file: 
      - .env
    volumes:
      - ..:/workspaces:cached
      - ../user_uploads:/user_uploads
    working_dir: /workspaces/fastapi
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
      - DB_INIT_RETRIES=30
      - DB_INIT_DELAY=2
    command: >
      sh -c "python -m db_manager.create_tables &&
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - linux-project-net                # 내부사용자가 사용하는 net
    depends_on:
      - db
    
  nginx:
    build:
      context: ..
      dockerfile: .devcontainer/nginx_env/Dockerfile 
    env_file: 
      - .env
    volumes:
      - ../nginx/src:/usr/share/nginx/html:ro  # nginx가 정적 파일을 읽을 수 있도록 src 폴더를 공유
      - ..:/workspaces:cached       # 전체 프로젝트 루트 공유
    environment:
      - PYTHONPATH=/workspaces         # 중요! /workspaces를 탐색 경로에 추가
    ports:
      - "80:80"
    networks:
      - linux-project-net
    depends_on:
      - db
  
volumes:
  postgres-linux-team-data:

networks:
  linux-project-net:
    driver: bridge